using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.parser;

namespace PDF_To_Text
{
    public partial class Form1 : Form
    {
        int pageCount = 1;
        public Form1()
        {
            InitializeComponent();
            DecryptFile();
        }

        public void ExtractTextFromPDFPage(string pdfFile, int pageNumber)
        {
            //PdfReader reader = new PdfReader(pdfFile);
            //PdfReader reader = new PdfReader(pdfFile, new System.Text.ASCIIEncoding().GetBytes("internet"));
            PdfReader reader = new PdfReader(pdfFile, new System.Text.UTF8Encoding().GetBytes("internet"));

            textBox1.Text += reader.PdfVersion;
            if (pageNumber==1) pageCount = reader.NumberOfPages;
            string text = PdfTextExtractor.GetTextFromPage(reader, pageNumber);
            try { reader.Close(); }
            catch { }
            this.richTextBox1.Text += text;
        }

        private void textBox1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyData == Keys.Enter)
            {
                //C:\Users\User\Google Drive\Бизим Маркет\2018 Oktyabr Kameral yoxlamalar\20.11.2018\2018 Mart\1819020829557200-autogenerateddocument.pdf.pdf
                //C:\sample.pdf
                ExtractTextFromPDFPage("c:\\samplePassword.pdf", 1);
                ExtractTextFromPDFPage("c:\\sample-unlocked.pdf", 1);
                ExtractTextFromPDFPage("c:\\sample.pdf", 1);
                ExtractTextFromPDFPage("c:\\sample1.pdf", 1); 
                ExtractTextFromPDFPage("c:\\sample2.pdf", 1);
                //for (int i = 1; i <= pageCount; i++)
                //{
                //    ExtractTextFromPDFPage(textBox1.Text, i);
                //}

            }
        }

        
        private void DecryptFile(string inputFile = "", string outputFile = "")
        {
            string WorkingFolder = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            string InputFile = "C:\\sample1.pdf";//Path.Combine(WorkingFolder, "test.pdf");
            string OutputFile = "C:\\samplePassword.pdf";//Path.Combine(WorkingFolder, "test_dec.pdf");//will be created automatically
                                                         //You must provide owner password but not the user password .
            inputFile = InputFile;
            outputFile = OutputFile;

            string password = @"secret"; // Your Key Here           
            try
            {
                //PdfReader reader = new PdfReader(inputFile, new System.Text.ASCIIEncoding().GetBytes(password));
                PdfReader reader = new PdfReader(inputFile, new System.Text.UTF8Encoding().GetBytes(password));

                using (MemoryStream memoryStream = new MemoryStream())
                {
                    PdfStamper stamper = new PdfStamper(reader, memoryStream);
                    stamper.Close();
                    reader.Close();
                    File.WriteAllBytes(outputFile, memoryStream.ToArray());
                }
            }
            catch (Exception /*err*/)
            {
                //Console.WriteLine(err.Message);
            }
        }
    }
}
